// 1. TYPE DEFINITIONS (Interfaces)
export interface RecipeIngredient {
  text: string;
}

export interface RecipeData {
  id: string;
  title: string;
  category: "Sweet" | "Savoury";
  ingredients: RecipeIngredient[];
  method: string[];
}

//2. THE MASTER RECIPE DATA ARRAY
export const ALL_RECIPES_DATA: RecipeData[] = [
  {
    id: "Boeber",
    title: "Boeber",
    category: "Sweet",
    ingredients: [
      { text: "125ml botter" },
      { text: "250ml vermicelli" },
      { text: "2 L melk" },
      { text: "8-10 kardemompe (fyn gekap)" },
      { text: "8-10 kaneelstukke" },
      { text: "250ml sago" },
      { text: "250ml suiker / kondensmelk (na smaak)" },
    ],
    method: [
      "Smelt die botter in 'n groot pot.",
      "Skroei die vermicelli in die botter tot dit ligbruin is.",
      "Gooi die melk, fyn gekapte kardemom en kaneelstukke by.",
      "Bring die mengsel tot kookpunt.",
      "Voeg die sago en suiker (of kondensmelk) by.",
      "Kook verder en roer gereeld tot die sago sag is.",
      "Voeg warm melk by indien die Boeber te dik word.",
    ],
  },
  {
    id: "CremoraTert",
    title: "Cremora-tert",
    category: "Sweet",
    ingredients: [
      { text: "1 koppie Cremora" },
      { text: "1½ koppies kookwater" },
      { text: "1 blik kondensmelk" },
      { text: "3 tlp.s suurlemoensap" },
      { text: "Tennisbeskuitjies (vir basis en krummels)" },
    ],
    method: [
      "Berei 'n basis van fyngemaakte Tennisbeskuitjies in 'n tertbak.",
      "Meng die Cremora en kookwater deeglik.",
      "Laat die Cremora-mengsel heeltemal afkoel en klits dit dan styf.",
      "Voeg die kondensmelk en suurlemoensap by die styfgeklopte Cremora en meng goed.",
      "Skep die mengsel in die beskuitbasis.",
      "Krummel oorskiet Tennisbeskuitjies bo-oor die tert.",
      "Plaas in die yskas om te stol.",
    ],
  },
  {
    id: "DawnseBranMuffins",
    title: "Dawn se Bran Muffins",
    category: "Sweet",
    ingredients: [
      { text: "500ml Nutty Wheat Meel" },
      { text: "250ml Suiker (1 k.)" },
      { text: "1 tlp. bakpoeier" },
      { text: "1 tlp. koeksoda" },
      { text: "250ml wortels/ neute/ piesangs/ dadels (gerasper)" },
      { text: "250ml Melk" },
      { text: "50ml Kookolie" },
      { text: "1 eier" },
    ],
    method: [
      "Voorverhit oond tot 180°C.",
      "Meng en klits melk, kookolie en eier.",
      "Voeg droë bestandele en meng goed.",
      "Bak +-30min.",
    ],
  },
  {
    id: "GeskroeideVermicelli",
    title: "Fried Geskroeide Vermicelli",
    category: "Sweet",
    ingredients: [
      { text: "250g botter" },
      { text: "Kaneel (stokkies of fyn)" },
      { text: "Kardemom (heel of fyn)" },
      { text: "250g vermicelli" },
      { text: "Suiker (na smaak)" },
      { text: "500ml water" },
    ],
    method: [
      "Smelt die botter in 'n pot.",
      "Voeg die kaneel en kardemom by.",
      "Voeg die vermicelli by en skroei dit in die botter tot dit lig- tot goudbruin is.",
      "Voeg die suiker en water by die vermicelli.",
      "Laat dit prut en stoom, met die deksel op, totdat die vermicelli gaar en die water geabsorbeer is (droog gestoom is).",
    ],
  },
  {
    id: "GemmerPoeding",
    title: "Gemmer Poeding",
    category: "Sweet",
    ingredients: [
      { text: "250ml koekmeel" },
      { text: "1 etl. appelkooskonfyt" },
      { text: "1 etl. Golden Syrup" },
      { text: "1 etl. botter" },
      { text: "1 tlp. fyn gemmer" },
      { text: "1 tlp. koeksoda" },
      { text: "½ koppie melk" },
      { text: "250ml suiker (stroop)" },
      { text: "250ml Water (stroop)" },
    ],
    method: [
      "Voorverhit oond tot 180°C.",
      "Meng botter, konfyt en Golden Syrup.",
      "Voeg gemmer en koeksoda by.",
      "Meng melk by ander bestanddele.",
      "Meng suiker en water [vir die stroop].",
      "Gooi [die stroop] bo-oor [die poedingmengsel].",
      "Bak 30 minute (180°C).",
    ],
  },
  {
    id: "HoenderVindaloo",
    title: "Hoender Vindaloo",
    category: "Savoury",
    ingredients: [
      { text: "Hoender (stukke of filette)" },
      { text: "Nat Masala (bv. gemmer, knoffel, brandrissies)" },
      { text: "Droë Masala (bv. komyn, koljander, speserye, borrie)" },
      { text: "Asyn (vir marinering)" },
      { text: "Ghee (geklaarde botter, vir braai)" },
      { text: "Uie (gekap)" },
      { text: "Rys (vir bediening)" },
      { text: "Koljander (vir garnering/bediening)" },
    ],
    method: [
      "Meng die nat en droë masalas met asyn om die marinade te vorm.",
      "Marineer die hoenderstukke vir 24 uur in die masala-mengsel.",
      "Braai die gemarineerde hoender in ghee tot dit begin verbruin.",
      "Voeg die oorblywende marinade en die gekapte uie by.",
      "Stowe die kerrie stadig oor lae hitte totdat die hoender sag en gaar is.",
      "Bedien warm met rys en vars koljander.",
    ],
  },
  {
    id: "Jogurttert",
    title: "Jogurttert",
    category: "Sweet",
    ingredients: [
      { text: "500ml jogurt (verkieslik gegeurde of dik jogurt)" },
      { text: "2 pak jellie (enige geur)" },
      { text: "1 blik kondensmelk" },
      { text: "1 koppie warm water (vir die jellie)" },
      { text: "Tennisbeskuitjies (vir die kors)" },
      { text: "1 blik pynappelstukke (met sap)" },
      { text: "1 tlp. vlapoeier (custard powder)" },
      { text: "1 tlp. sout (vir die pynappelmengsel)" },
    ],
    method: [
      "Berei die kors voor met die Tennisbeskuitjies.",
      "Los die jellie op in die warm water.",
      "Voeg gelyke hoeveelheid koue water by die jellie (as wat op die verpakking aanbeveel word).",
      "Meng die kondensmelk en jogurt saam.",
      "Voeg die effens afgekoelde jellie by die jogurtmengsel en roer goed.",
      "Giet die jogurtmengsel oor die beskuitjiekors en laat dit begin stol.",
      "Verhit die pynappel met die vlapoeier en sout tot dit verdik.",
      "Skep die pynappelmengsel bo-oor die gestolde tert.",
      "Verkoel tot ferm.",
    ],
  },
  {
    id: "KaapseBrandewynpoeding",
    title: "Kaapse Brandewynpoeding",
    category: "Sweet",
    ingredients: [
      { text: "250g Dadels, ontpit en fyngekap" },
      { text: "5ml koeksoda" },
      { text: "250ml kookwater" },
      { text: "250ml suiker" },
      { text: "250ml meel" },
      { text: "250ml okkerneute, gekap" },
      { text: "250ml [meel/botter - ontbrekende item in oorspronklike HTML]" },
      { text: "125g botter" },
      { text: "2 eiers (geklits)" },
      { text: "5ml bakpoeier" },
      { text: "5ml sout" },
      { text: "2ml sout" },
    ],
    method: [
      "Voorverhit die oond tot 180°C.",
      "Poeding: Meng die nat en droë bestanddele goed saam (insluitend die okkerneute).",
      "Plaas in 'n gesmeerde oondbak en bak vir 40 minute.",
      "Sous: Meng al die sousbestanddele en verhit tot die botter gesmelt en die suiker opgelos is.",
      "Gooi die warm sous oor die warm poeding sodra dit uit die oond kom.",
    ],
  },
  {
    id: "KlapperVulsel",
    title: "Klapper (Pannekoek-vulsel)",
    category: "Sweet",
    ingredients: [
      { text: "½ pak klapper (gesnipperde klapper)" },
      { text: "½ koppie suiker" },
      { text: "1 koppie water" },
      { text: "Kaneelstokkies" },
      { text: "Kardemompitjies" },
    ],
    method: [
      "Voeg die klapper, suiker, water, kaneelstokkies en kardemompitjies in 'n pot.",
      "Kook die mengsel oor medium hitte tot dit begin stroperig raak.",
      "Roer gereeld sodat die klapper nie aanbrand nie.",
      "Verwyder die kaneelstokkies en kardemompitjies voordat dit as vulsel gebruik word.",
    ],
  },
  {
    id: "KorsloseSouttert",
    title: "Korslose Souttert",
    category: "Savoury",
    ingredients: [
      { text: "500ml gerasperde Weense worsies" },
      { text: "3 eiers" },
      { text: "500ml gerasperde kaas" },
      { text: "125ml spek (gekap en gebraai)" },
      { text: "250ml melk" },
      { text: "12.5ml mosterdpoeier" },
      { text: "2 tlp.s asyn" },
      { text: "10ml pietersielie (fyngekap)" },
      { text: "30ml meel" },
      { text: "Sout en peper (na smaak)" },
    ],
    method: [
      "Meng alle bestanddele deeglik saam.",
      "Giet die mengsel in 'n gesmeerde tertbak.",
      "Bak vir 30-35 minute by 180°C, of tot die tert gestol en goudbruin is.",
    ],
  },
  {
    id: "MaaskaasTert",
    title: "Maaskaas Tert",
    category: "Sweet",
    ingredients: [
      { text: "1 blik kondensmelk" },
      { text: "1 pak Orley Whip" },
      { text: "1 houer maaskaas" },
      { text: "1 pak gelatien" },
      { text: "1 pak rooi jellie" },
      { text: "1 koppie kookwater (vir die jellie)" },
    ],
    method: [
      "Berei die tennisbeskuitkors voor (metode nie gespesifiseer, maar implisiet).",
      "Meng die kondensmelk, Orley Whip, maaskaas en gelatien goed saam.",
      "Giet die mengsel in die kors en laat oornag staan (om te stol).",
      "Berei die rooi jellie met 1 koppie kookwater.",
      "Gooi die voorbereide jellie bo-oor die tert sodra dit gestol is.",
    ],
  },
  {
    id: "MalvaLekkerTert",
    title: "Malva Lekker Tert",
    category: "Sweet",
    ingredients: [
      { text: "1 blik kondensmelk" },
      { text: "125ml suurlemoensap" },
      { text: "150g malvalekkers" },
      { text: "250ml vars room" },
      { text: "125ml fyn pynappelstukke" },
    ],
    method: [
      "Klits kondensmelk en suurlemoensap tot dik.",
      "Vou die malvalekkers in die kondensmelk-mengsel.",
      "Klits die vars room tot styf.",
      "Voeg die geklitste room by die kondensmelk-mengsel.",
      "Meng goed en roer die pynappelstukke by.",
      "Plaas oornag in die yskas om te stol.",
    ],
  },
  {
    id: "Malvapoeding",
    title: "Malvapoeding",
    category: "Sweet",
    ingredients: [
      { text: "1 koppie koekmeel" },
      { text: "1 tlp. bakpoeier" },
      { text: "1 tlp. koeksoda" },
      { text: "Knippie sout" },
      { text: "¾ koppie suiker" },
      { text: "¾ koppie kookolie" },
      { text: "1 koppie melk" },
      { text: "1 eier" },
      { text: "1 etl. appelkooskonfyt" },
    ],
    method: [
      "Meng die droë bestanddele (meel, bakpoeier, koeksoda, sout, en suiker) saam.",
      "Klits die olie, melk, eier en appelkooskonfyt.",
      "Meng die nat en droë bestanddele saam tot net gemeng.",
      "Giet die beslag in 'n gesmeerde oondbak en bak vir 40-45 minute by 180°C (temperatuur nie gespesifiseer, maar implisiet).",
      "Verhit die sousbestanddele saam totdat die botter gesmelt en die suiker opgelos is.",
      "Gooi die warm sous oor die warm poeding sodra dit uit die oond kom.",
    ],
  },
  {
    id: "MikrogolfSjokoladekoek",
    title: "Mikrogolf Sjokoladekoek",
    category: "Sweet",
    ingredients: [
      { text: "250ml koekmeel" },
      { text: "250ml suiker" },
      { text: "4 tlp.s bakpoeier" },
      { text: "4 tlp.s kakao" },
      { text: "2 eiers" },
      { text: "100ml kookolie" },
      { text: "250ml kookwater" },
    ],
    method: [
      "Klits kookpolie en kookwater saam",
      "Meng ander bestanddele saam en klits tot glad.",
      "Mikrogolf vir 7 minute op HOOG.",
    ],
  },
  {
    id: "Noedelslaai",
    title: "Noedelslaai",
    category: "Savoury",
    ingredients: [
      { text: "500g noedels (gaar en gedreineer)" },
      { text: "Uie (gekap)" },
      { text: "Greenpepper (groen soetrissie, gekap)" },
    ],
    method: [
      "Kook die noedels volgens aanwysings en dreineer.",
      "Braai die gekapte uie en greenpepper tot sag.",
      "Meng al die sousbestanddele in 'n pot en laat dit prut tot dit verdik.",
      "Meng die gaar noedels, gebraaide groente en die warm sous deeglik saam.",
      "Laat afkoel en bedien koud.",
    ],
  },
  {
    id: "Pampoenkoekies",
    title: "Pampoenkoekies",
    category: "Sweet",
    ingredients: [
      { text: "2 koppies gaar, fyngemaakte pampoen" },
      { text: "4 etl. koekmeel / self-raising meel" },
      { text: "2 tlp. bakpoeier" },
      { text: "Knippie sout" },
      { text: "1 eier" },
      { text: "Kaneelsuiker (vir bo-oor)" },
    ],
    method: [
      "Meng die pampoen, meel, bakpoeier en sout. Die mengsel moet styf wees.",
      "Klits die eier en voeg dit by die pampoenmengsel.",
      "Drup lepels vol van die beslag in warm olie.",
      "Braai tot goudbruin en gaar.",
      "Strooi kaneelsuiker oor terwyl dit warm is.",
    ],
  },
  {
    id: "Pannekoek",
    title: "Pannekoek",
    category: "Sweet",
    ingredients: [
      { text: "1 koppie meel" },
      { text: "¾ tlp. bakpoeier" },
      { text: "½ tlp. sout" },
      { text: "1 koppie melk" },
      { text: "1 eier" },
      { text: "Kaneelsuiker (vir bediening)" },
    ],
    method: [
      "Meng alle bestanddele en klits goed tot 'n gladde beslag.",
      "Bak lepelsvol van die beslag in 'n warm pan [met 'n bietjie olie of botter].",
      "Bedien warm, besprinkel met kaneelsuiker.",
    ],
  },
  {
    id: "Pynappeltert",
    title: "Pynappeltert (Pineapple Treat)",
    category: "Sweet",
    ingredients: [
      { text: "1 blik Ideal Milk (baie koud)" },
      { text: "1 blik Koo-pynappels (fyn of stukke)" },
      { text: "2 pak pynappeljellie" },
      { text: "Tennisbeskuit (vir die kors)" },
      { text: "[Orley Whip] (vir bo-oor - opsioneel/vermoedelik)" },
    ],
    method: [
      "Berei die kors met die tennisbeskuit voor.",
      "Maak die jellie aan met 2 koppies kookwater en laat afkoel tot dit begin stol.",
      "Klits die koue Ideal Milk styf.",
      "Sny die pynappel, met die stroop, in die beginnende gestolde jellie.",
      "Voeg die pynappel-en-jelliemengsel by die geklopte Ideal Milk.",
      "Giet die mengsel op die beskuitkors en laat stol.",
      "Smeer Orley Whip bo-oor voor bediening.",
    ],
  },
  {
    id: "SagoPoeding",
    title: "Sago-poeding",
    category: "Sweet",
    ingredients: [
      { text: "1 sakkie melk (gewoonlik 1 liter)" },
      { text: "1 koppie sago" },
      { text: "1 koppie suiker" },
      { text: "Kaneelstukke (of fyn kaneel)" },
      { text: "4 eiers" },
    ],
    method: [
      "Week die sago vir 'n paar uur of oornag in water (dreineer dit voor gebruik).",
      "Verhit die melk in 'n pot met die kaneelstukke.",
      "Voeg die geweekte sago en suiker by die warm melk. Kook oor lae hitte en roer tot die sago deurskynend is.",
      "Haal die mengsel van die hitte en laat dit effens afkoel.",
      "Klits die eiers en voeg dit by die sago-mengsel sodra dit effens afgekoel het (om te keer dat die eier kook).",
      "Giet die mengsel in 'n gesmeerde oondbak en bak vir 1 uur [by 'n geskikte temperatuur, soos 180°C].",
    ],
  },
  {
    id: "SnoekEnAppelkoosjam",
    title: "Snoek & Appelkoosjam (Deon Maas)",
    category: "Savoury",
    ingredients: [
      { text: "1 vars snoek (oopgesny)" },
      { text: "2 koppies growwe sout (vir vryf/pekel)" },
      { text: "Olie (vir braai)" },
      { text: "Peper (vir vryf - implisiete bestanddeel)" },
    ],
    method: [
      "Bereiding van Sous: Smelt al die bedruipsous-bestanddele saam in 'n pot en laat dit vir 20 minute prut om die geure te ontwikkel.",
      "Bereiding van Vis: Vryf die snoek met growwe sout, peper en olie.",
      "Braai: Braai die snoek oor matige kole vir 20-25 minute, met die velkant na onder vir die grootste deel van die tyd.",
      "Bedruip die vis gereeld met die appelkoosjam-sous tydens die laaste deel van die braaityd.",
      "Bedien warm met die orige sous en vars suurlemoenwiggies.",
    ],
  },
  {
    id: "SunriseSurprise",
    title: "Sunrise Surprise",
    category: "Savoury",
    ingredients: [
      { text: "1 Franse brood (Franse stokbrood)" },
      { text: "Botter" },
      { text: "1 pakkie spek" },
      { text: "4 eiers" },
      { text: "2ml warm sous (bv. Tabasco)" },
      { text: "Sout en peper (na smaak)" },
      { text: "Paprika" },
      { text: "Cayennepeper" },
      { text: "Kaas (gerasper of in skywe)" },
      { text: "1 tamatie (vir garnering/bediening)" },
      { text: "Blaarslaai (vir bediening)" },
      { text: "[1 ui, gekap] (Implisiete bestanddeel in metode)" },
      { text: "[Koljander] (Implisiete bestanddeel vir garnering)" },
    ],
    method: [
      "Sny die Franse brood in skywe en smeer met botter.",
      "Braai die spek en plaas dit in 'n oondbak, bo-op die botterbrood.",
      "Klits die eiers saam met die warm sous, sout, peper, paprika, cayennepeper, kaas en gekapte ui.",
      "Skep die eiermengsel oor die brood en spek in die oondbak.",
      "Bak tot die eiers gestol en goudbruin is.",
      "Garneer met koljander, en bedien saam met snye tamatie en blaarslaai.",
    ],
  },
  {
    id: "TuisgemaakteDadels",
    title: "Tuisgemaakte Dadels",
    category: "Sweet",
    ingredients: [
      { text: "125g botter" },
      { text: "125g suiker" },
      { text: "250g pitlose dadels, gekap" },
      { text: "125ml water" },
      { text: "200g Marie-beskuitjies, gebreek" },
    ],
    method: [
      "Verhit die botter en suiker vir 5 minute saam.",
      "Voeg die gekapte dadels by en kook vir 3 minute.",
      "Roer die water en die gebreekte Marie-beskuitjies by die dadelmengsel.",
      "Druk die mengsel vas in 'n pan (of rol dit in 'n stomp).",
      "Laat dit volledig afkoel en stol voordat dit in blokkies of skywe gesny word.",
    ],
  },
  {
    id: "TunaTert",
    title: "Tuna Tert",
    category: "Savoury",
    ingredients: [
      { text: "2 snye witbrood (opgebreek)" },
      { text: "½ koppie melk" },
      { text: "1 blik tuna (gedreineer)" },
      { text: "2 eiers (geklits)" },
      { text: "1 koppie kaas (gerasper)" },
      { text: "1 ui (fyngekap)" },
      { text: "Speserye (bv. sout, peper, paprika)" },
    ],
    method: [
      "Week die opgebreekte witbrood in die melk tot sag.",
      "Voeg die gedreineerde tuna, geklitste eiers, gekapte ui, die helfte van die kaas en die speserye by die broodmengsel. Meng goed.",
      "Giet die mengsel in 'n gesmeerde tertbak.",
      "Strooi die res van die kaas bo-oor die tert.",
      "Bak vir 30 minute [by 'n geskikte temperatuur, gewoonlik 180°C / 350°F].",
    ],
  },
  {
    id: "TunaVorm",
    title: "Tuna Vorm",
    category: "Savoury",
    ingredients: [
      { text: "1 blik tuna (gedreineer)" },
      { text: "1 houer maaskaas" },
      { text: "1 ui, gekap" },
      { text: "3 etl.s mayonnaise" },
      { text: "4 etl.s tamatiesous" },
      { text: "10g gelatien, opgelos in ½ koppie kookwater" },
    ],
    method: [
      "Kap die ui fyn.",
      "Meng die maaskaas, gedreineerde tuna, gekapte ui en mayonnaise goed saam.",
      "Voeg die tamatiesous en die opgeloste gelatien by die mengsel. Roer deeglik.",
      "Giet die mengsel in 'n vorm (of bak) en plaas in die yskas.",
      "Laat dit stol, verkieslik oornag.",
    ],
  },
  {
    id: "VinnigeSouttert1",
    title: "Vinnige Souttert (1)",
    category: "Savoury",
    ingredients: [
      { text: "1 sny witbrood (opgebreek)" },
      { text: "250ml melk" },
      { text: "250ml gesmelte botter" },
      { text: "250ml gerasperde kaas" },
      { text: "3 eiers, geklits" },
      {
        text: "Vulsel: Bacon / polony / hoender / uie / greenpepper (vooraf gebraai)",
      },
    ],
    method: [
      "Voeg melk en botter by die brood en laat dit week tot sag.",
      "Voeg die kaas en die geklitste eiers by die broodmengsel.",
      "Voeg die vleis- en groentemengsel (bacon / polony / hoender / uie / greenpepper) by en meng goed.",
      "Giet die mengsel in 'n gesmeerde pan (of bakskottel).",
      "Bak vir 35 minute [by 'n geskikte temperatuur, gewoonlik 180°C / 350°F].",
    ],
  },
  {
    id: "VinnigeSouttert2",
    title: "Vinnige Souttert (2)",
    category: "Savoury",
    ingredients: [
      { text: "250g streepspek, gekap" },
      { text: "1 ui, gekap" },
      { text: "250g sampioene of Weense worsies" },
      { text: "15ml botter" },
      { text: "30ml gemengde droë kruie" },
      { text: "Peper na smaak" },
      { text: "500ml gerasperde cheddar" },
      { text: "2 eiers" },
      { text: "250ml melk" },
      { text: "50ml bruismeel (self-raising flour)" },
    ],
    method: [
      "Braai die spek of vleis in die botter. Voeg die ui en sampioene/worsies by en braai tot sag.",
      "Voeg die kruie en peper by die vleismengsel.",
      "Pak die vulsel eweredig in 'n gesmeerde oondbak.",
      "Strooi die gerasperde kaas oor die vulsel.",
      "Klits die eiers, melk en bruismeel saam.",
      "Gooi die eiermengsel oor die kaas en vulsel in die oondbak.",
      "Bak vir 30 minute teen 180°C.",
    ],
  },
  {
    id: "MikrogolfWortelkoek",
    title: "Mikrogold Wortelkoek",
    category: "Sweet",
    ingredients: [
      { text: "1/2 koppie kookolie" },
      { text: "3/4 koppe bruinsuiker" },
      { text: "1/2 tlp. koeksoda" },
      { text: "1 tlp. Valilla essens" },
      { text: "1 tlp Gemengde Speserye" },
      { text: "1 tlp. Fyn Kaneel" },
      { text: "1 koppie Selfraising meel" },
      { text: "2 koppies Gerasperde Wortels" },
      { text: "100ml Gekapte neute" },
    ],
    method: ["Klits alles saam", "Bak 7 min op hoog"],
  },
];
